# Portable Prolog System.

MODULES = prolog.o util.o malloc.o catchint.o

prolog: $(MODULES)
	pc -o prolog $(MODULES)

prolog.o: util.h catchint.h libname.h
util.o: cdefs.h
malloc.o: malloc.h

clean:
	rm *.o

dist_clean: clean
	rm prolog

.p.o:
	pc -c -w $*.p

.SUFFIXES: .p .o .c
